name = "Swag Pack"
author = "24minecraftsam"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "14246d983d9d318dc11c4072526045546234e77bbfaf38681a06b0dc3f5ddbc5"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
