name = "Swag Pack"
author = "24minecraftsam"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a454b58206552a505a3e3a33b0a8ad948e1fbd070d8b46e21e9698801cd5e48f"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0-beta.1"
