name = "Swag Pack"
author = "24minecraftsam"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fe86eb96efbd7381fe380228e2d806ed3f50091cd7ed459b5abcba05c0c0ed6e"

[versions]
minecraft = "1.20.1"
quilt = "0.23.0"

[options]
acceptable-game-versions = ["1.20", "1.20.1"]
