id: DIRTY_GRASS
type: PALETTE

layers:
  - materials:
      - minecraft:grass_block: 20
      - minecraft:coarse_dirt: 4
    layers: 1
    sampler:
      type: OPEN_SIMPLEX_2
      frequency: 0.05

  - materials:
      - minecraft:dirt: 2
    layers: 1
  - materials:
      - minecraft:stone: 1
    layers: 1